### ISSUE TITLE
Cannot make migration

### ISSUE THREAD

**Issue by GoldeNx3** [khsing/laravel-world#4] opened 2018-03-12 11:43 UTC
Hello, after write in composer "php artisan world:init" cmd shows me this:

"PDOException::("SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x87\xA8\xF0\x9F...' for column 'emoji' at row 1")"

How to fix it?

**Comment by khsing** [comment] 2018-07-28 04:32
Duplicate of #3 , using utf8mb4 as default mysql database charset.

**Closed as completed by khsing** 2018-07-28 04:32 UTC
